# =============================================================================
# ARGOCD INSTALLATION - Setting up ArgoCD in your cluster
# =============================================================================
# ArgoCD runs as a set of controllers inside your Kubernetes cluster.
# It watches Git repositories and keeps the cluster in sync with the
# desired state defined in those repos.
#
# Installation steps:
#   1. Create the argocd namespace
#   2. Apply the official install manifest
#   3. Access the UI via port-forward
#   4. Get the initial admin password
#
# This file creates just the namespace. The actual ArgoCD components
# are installed from the official manifest (see commands below).
# =============================================================================

# --- Step 1: Create the ArgoCD namespace ---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    purpose: gitops-controller

# =============================================================================
# INSTALLATION COMMANDS (run these in order):
#
# 1. Apply this namespace:
#    kubectl apply -f argocd/install.yaml
#
# 2. Install ArgoCD from official manifest:
#    kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
#
# 3. Wait for all Pods to be ready:
#    kubectl wait --for=condition=Ready pods --all -n argocd --timeout=120s
#
# 4. Get the initial admin password:
#    kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
#
# 5. Port-forward to access the UI:
#    kubectl port-forward svc/argocd-server -n argocd 8080:443
#
# 6. Open https://localhost:8080 in your browser
#    Username: admin
#    Password: (from step 4)
#
# ARGOCD CLI INSTALLATION:
#   macOS:   brew install argocd
#   Linux:   curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
#            chmod +x argocd && sudo mv argocd /usr/local/bin/
# =============================================================================
